### PR TITLE
Support the uncooked assets

### PR DESCRIPTION
**Pull request by rndtrash**
This PR adds a support for the assets that were not cooked. I'm not sure if you want them to be supported, but I found it weird that UAssetGUI didn't support these, so here it is.

What works:
- Assets straight from the Content folder of a UE 4.27.2 project: Material, SoundClass, Actor Blueprint
- Thumbnails

What doesn't work yet:
- Searchable names. Right now it works only for the assets that have 0 names.
- Gatherable text data metadata. I haven't encountered any asset that has any of these yet.

What hasn't been tested yet:
- Thumbnails and gatherable text data serialization to JSON

References:

https://github.com/EpicGames/UnrealEngine/blob/072300df18a94f18077ca20a14224b5d99fee872/Engine/Source/Runtime/CoreUObject/Private/UObject/SavePackage2.cpp#L1890

https://github.com/EpicGames/UnrealEngine/blob/072300df18a94f18077ca20a14224b5d99fee872/Engine/Source/Runtime/CoreUObject/Private/UObject/SavePackage/SavePackageUtilities.cpp#L1777

https://github.com/EpicGames/UnrealEngine/blob/4.27.2-release/Engine/Source/Runtime/CoreUObject/Private/UObject/PackageFileSummary.cpp#L197

### CODE REVIEW

**Comment by rndtrash** [comment]
Sorry, misclicked 😓

**Comment by rndtrash** [comment]
The blueprint test case still fails: it seems to lose 4 bytes between the soft package references and the thumbnail sections.
image

**Comment by rndtrash** [comment]
I figured it out, and now all that's left is one unparsed export.

**Review by atenfyr — APPROVED** [review]

**Comment by atenfyr** [comment]
great work. I'll see if I can't get some of these other exports to parse

**Pull request merged**
